baseurl = "https://pablosanjose.com/"
copyright = "Pablo San Jose - 2021 - {year}"
languageCode = "en-us"
theme = "codex"
title = "Pablo San Jose"

disableAliases = true

[markup]
[markup.highlight]
codeFences = true
guessSyntax = true
noClasses = true
style = "dracula"
tabWidth = 2

[related]
includeNewer = true
threshold = 80
toLower = true

[[related.indices]]
name = "keywords"
weight = 10

[permalinks]
post = "/posts/:slug"

[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true

[params]
author = "Pablo San Jose"
avatar = "avatar.jpg"
description = "My personal website and blog. Welcome!"
email = "mailto:hi@pablosanjose.com?subject=Hi!"
github = "https://bit.ly/github-pablosjv"
iconOrder = ["email", "linkedin", "GitHub"]
keywords = "software development, software, machine learning, python, data engineer, golang, devops, go"
linkedin = "https://bit.ly/linkedin-pablosjv"
stackexchange = "https://bit.ly/stackoverflow-pablosjv"

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "resume"
name = "Resume"
url = "/resume/"
weight = 30

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 40

[outputs]
home = ["HTML", "RSS"]
