# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.80.0"
          extended: true

      - uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - run: make setup ci
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BLOG_COLLECTION_ID: ${{ secrets.BLOG_COLLECTION_ID }}
          BLOG_COLLECTION_VIEW_ID: ${{ secrets.BLOG_COLLECTION_VIEW_ID }}
          OTHER_COLLECTION_ID: ${{ secrets.OTHER_COLLECTION_ID }}
          OTHER_COLLECTION_VIEW_ID: ${{ secrets.OTHER_COLLECTION_VIEW_ID }}
