name: refresh

on:
  push:
    branches: [master]
  # schedule:
  #   - cron: "0 0 */1 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: "recursive"

      - name: Install python and dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Version range or exact version of a Python version to use, using SemVer's version range syntax

      - name: Refresh Notion pages
        run: make setup refresh
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BLOG_COLLECTION_ID: ${{ secrets.BLOG_COLLECTION_ID }}
          BLOG_COLLECTION_VIEW_ID: ${{ secrets.BLOG_COLLECTION_VIEW_ID }}
          OTHER_COLLECTION_ID: ${{ secrets.OTHER_COLLECTION_ID }}
          OTHER_COLLECTION_VIEW_ID: ${{ secrets.OTHER_COLLECTION_VIEW_ID }}

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.8.0
        with:
          commit_message: "chore: refresh with notion"
          branch: master
